ProxyPass        /rymdresan/api/ http://127.0.0.1:8001/rymdresan/api/ connectiontimeout=3 timeout=10
ProxyPassReverse /rymdresan/api/ http://127.0.0.1:8001/rymdresan/api/

Alias /rymdresan/highscores.json /var/lib/rymdresan/public/highscores.json
<Directory /var/lib/rymdresan/public>
    Require all denied
    <Files "highscores.json">
        Require all granted
        ForceType application/json
        Header always set Cache-Control "no-cache"
        Header always set Access-Control-Allow-Origin "*"
    </Files>
</Directory>

<Directory /var/www/html/rymdresan>
    Require all granted
    Options -Indexes +FollowSymLinks
</Directory>
